<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/vendor/autoload.php';

/**
 * 设置路径
 *
 * @param $file
 * @return string
 */
function storage_path($file)
{
    $dir    = dirname(dirname(dirname(dirname(__DIR__))));
    $file   = $dir. '/storage' . $file;

    if (is_dir($dir) ) {
        if (is_writable($dir)) {
            return $file;
        } else {
            throw  new InvalidArgumentException('文件不可写！' . $file);
        }
    } else {
        throw  new InvalidArgumentException('目录不存在！');
    }

}
